### ISSUE TITLE
HitQueuing Disabled/enabled state support

### ISSUE THREAD

**Issue by nporter-adbe** [adobe/aepsdk-core-ios#125]
Add the ability for HitQueueing to be put in a disabled and enabled state. When the queue is disabled it will ignore all incoming queued hits.

**Comment by shalehaha** [comment]
@nporter-adbe do we still need this enhancement?

**Comment by nporter-adbe** [comment]
@shalehaha I don't think we need this. Feel free to re-open if you think otherwise.
