### ISSUE TITLE
implement app state detection

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#229]
similar thing as the current `ADBSystemNotificationHandler`, but should make it cleaner.

**Comment by nporter-adbe** [comment]
Talked with the team implementing Analytics and since we are in Swift/native code it might be overkill to have a dedicated service to read the app state. For now, we are deferring this service in favor of just reading the app state directly ` [[UIApplication sharedApplication] applicationState]`.

**Comment by shalehaha** [comment]
@nporter-adbe  it works for now, but I guess eventually we might still want to provide something in Services where we listen for the notifications. 

1. `[[UIApplication sharedApplication] applicationState]` needs to run on the main thread, it might be not easy for an extension to run it on the main thread, and after that switch back to the extension thread. Also, it is not a good practice to keep bothering the main thread unless necessary.
2. Watch doesn't support this API, so we will need to use Macros to maintain the code in the future.

**Comment by praveek** [comment]
This functionality is currently not needed by other extensions. We can reopen this if needed.
