### ISSUE TITLE
E2E test: Explore using Griffon to verify the behavior of swift SDK is the same with V5

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#246]

**Comment by cdhoffmann** [comment]
As of right now the process to compare the events between v5 and Swift SDK is a manual process. These are the steps i took to compare:

1. Set up the v5 SDK with an app of your choosing
2. Set up the Swift SDK with the same app
3. Make sure the API calls are in the same places between the apps as to replicate the same behavior during the use of each app. What i did was use the Swift Sample app and configured it to use the v5 SDK on a separate git branch.
4. Create a Griffon session 
5. Hook up an app with the Griffon session and follow specific reproducible steps in the app triggering the API calls.
6. Take note of the time when starting the next step
7. Hook up the other app with the same Griffon session and follow the same steps as step 5.
8. The Griffon session should now have the events to be compared

From here the steps are more flexible and you can follow whatever recourse you'd like. Here is what i did:

9. Sort Griffon events by type. Observe to make sure that the same events exist from each source (v5 and Swift) and that they are named the same. 
10. Once you know that events are matching and named the same, it is time to compare payload data.
11. For this step you can simply follow the same steps as before but with a separate session for each SDK. Once you have the events in each session, download the event JSON using the `Export to JSON` utility on the events tab in Griffon.
12. Now use a JSON diff tool to compare the events between two sessions. I used this one: http://www.jsondiff.com/
