### ISSUE TITLE
Handle Edge vs direct flow in Identity

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#414]
Turn off direct calls when Edge is enabled.
Part of https://github.com/adobe/aepsdk-core-ios/issues/391

**Comment by nporter-adbe** [comment]
For this task, I assume we need to turn off network requests for Identity when Edge is present, correct? Is there any additional functionality in Identity that needs to be disabled when Edge is present?

**Comment by emdobrin** [comment]
That is correct, direct network calls to Experience ID Service will be turned off and the existing visitor identifiers, ECID etc need to be converted to XDM IdentityMap. When the Identity APIs are called, the data should be made available through both shared state formats.
