### ISSUE TITLE
Convert EdgeHost to locationHint

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#415]
Convert EdgeHost to locationHint for backwards compatibility
Part of https://github.com/adobe/aepsdk-core-ios/issues/391

**Comment by nporter-adbe** [comment]
@emdobrin Can we get more details on this issue?
1. Where does EdgeHost come from? E.g. how should we read it? 
2. Should we replace the value for locationHint with the value we read in for EdgeHost

**Comment by emdobrin** [comment]
This task is no longer needed, AEP Identity extension should be used for locationHint
