### ISSUE TITLE
visitoridslist has [AEPIdentity.CustomIdentity] type in Identity shared state

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#433]
### Expected Behaviour
visitoridslist should have raw data format when sharing through Shared States

### Actual Behaviour
visitoridslist has [AEPIdentity.CustomIdentity] type in Identity shared state

### Reproduce Scenario (including but not limited to)
Using Swift core and a free form Data element in Launch for `~state.com.adobe.module.identity/visitoridslist` I noticed the returned value from the client is [AEPIdentity.CustomIdentity]

**Comment by emdobrin** [comment]
I updated my app to AEPIdentity v3.0.0-beta.1 and I observed the following shared state:
```
"visitoridslist": [Optional(["authentication.state": 0, "id": dc565042aa48e653af4d84a3ba8043757112006556aac9560084a1243e5fb773, "id.type": testEmail, "id.origin": d_cid_ic])]
```
The visitor ids lists in ACPCore were id, id_origin, id_type and authentication_state, so we will need to change the keys in AEPIdentity to match for backwards compatibility.

**Comment by nporter-adbe** [comment]
@emdobrin thanks for bringing this up, I checked the ACPCore code and it matches with the keys you have listed. Last week @cdhoffmann and I validated some stuff in Griffon and saw the visitor id list to look a bit different in V5. Here is a sample event from V5 in Griffon

Any idea why this is different? This is definitely from V5 as the event number is populated.

```
{
  "ACPExtensionEventUniqueIdentifier": "987D9364-423F-47AF-83BF-4BFD54FB6F97",
  "ACPExtensionEventNumber": 30,
  "ACPExtensionEventData": {
    "visitoridslist": [
      {
        "id": "1234567",
        "authentication.state": 1,
        "id.origin": "d_cid_ic",
        "id.type": "idType1"
      }
    ],
    "lastsync": 1603299546,
    "mid": "47638672570484457245556507411373198888",
    "blob": "j8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI",
    "locationhint": "9"
  },
  "ACPExtensionEventSource": "com.adobe.eventsource.responseidentity",
  "ACPExtensionEventName": "UPDATED_IDENTITY_RESPONSE",
  "ACPExtensionEventType": "com.adobe.eventtype.identity"
}
```

**Comment by nporter-adbe** [comment]
@emdobrin here is the Griffion session: https://experience.adobe.com/#/@obumobile5/griffon/session/d6d5c718-5ef8-49b8-a3dc-00f1964443f0/view/event-list

Search for event `F298462C-4859-490E-9041-982B00403205`

**Comment by nporter-adbe** [comment]
In the above griffon session, you can see that the Swift keys match the V5 keys in the Identity shared state and in the event.

**Comment by nporter-adbe** [comment]
Given that the Swift keys shown match what we see in Griffon (shared state and event data) for a existing v5 app I'm going to close this issue.

**Comment by emdobrin** [comment]
@shalehaha @nporter-adbe based on @praveek 's testing  this seems to still be an issue, the keys contain dot (.) instead of underscore (_) and this was not caught by Griffon validation because there is an issue where underscores are displayed as dots in the UI (see MOB-13372). I am reopening this issue

**Comment by nporter-adbe** [comment]
@emdobrin That's unfortunate Griffon was giving us inaccurate info. I'll create a PR to fix this.
