### ISSUE TITLE
Discussion: Move XDM base classes into Core 

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#439]
Move the XDM base protocol/classes into Core, so 
1. The XDM related API can use those classes (for example get/set XDM shared state)
2. In the future any extension that doesn't rely on Edge can also use XDM.

**Comment by shalehaha** [comment]
@pfransenadb anything else you want to add here?

**Comment by emdobrin** [comment]
@shalehaha I would postpone this discussion until we have more context from https://github.com/adobe/aepsdk-edge-ios/issues/100
