### ISSUE TITLE
log for unicode letters

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#518]
Need to decide how we should print Unicode letters in the log.
Current example, where content is Chinese ` 这是纯文本内容！`:
```
offers =             (
                                {
                    characteristics =                     {
                        testing = true;
                    };
                    content = "\U8fd9\U662f\U7eaf\U6587\U672c\U5185\U5bb9\Uff01";
                    id = "xcore:personalized-offer:12bad2a46e2469d7";
                    language =                     (
                        "zh-cn"
                    );
                    schema = "https://ns.adobe.com/experience/offer-management/content-component-text";
                    type = 2;
                }
            );
```

@swarna04

**Comment by yangyansong-adbe** [comment]
The above Unicode literals (e.g. `\U8fd9\U662f\U7eaf\U6587\U672c\U5185\U5bb9\Uff01`) exist in the event data or the JSON string of the network payload, and the logging service only accepts and prints which `String` you passed to it. So we'd better convert the "Unicode" literals to "String" literals before passing it to the logging service.
@shalehaha  I think we can close this issue, and let developers to decide which literals should be printed in logs.
