### ISSUE TITLE
Function to check network connection status.

### ISSUE THREAD

**Issue by shtomar-adb** [adobe/aepsdk-core-ios#549]
Is it in roadmap to implement a function for checking network connection status?

**Comment by nporter-adbe** [comment]
What's the use-case for this? IIRC Apple deprecating the methods for checking network status in favor of just attempting to send the network request and retry if needed.

Currently, I'm not aware of any extension that checks network status before sending a network status. The current recommendation would be to attempt to send the network request if it fails for any reason, retry at a later time.

@shalehaha thoughts?

**Comment by shtomar-adb** [comment]
It's been checked in ACPMedia before sending media analytics hit. If the recommendation from Apple is to let it fail, then we can think about implementing that way.

**Comment by shalehaha** [comment]
It'd better to just try and fail. Reachability is not 100% reliable either.
