### ISSUE TITLE
CI/CD - Swift lint / swift format

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#554]
Current core setup uses both swift lint and swift format for formatting. While both of them have various useful rules for formatting, when using both you can easily run into conflicts and one of them can invalidate the output of the other. 
This may become an issue when you run these two commands in a certain order on the local machine, but the CI executes them in another order.

Based on https://github.com/adobe/aepsdk-core-ios/issues/67#issuecomment-671520955 we decided to use only Swift Lint for now in the Edge project, until we find a need for more granular formatting rules.

Additionally I noticed that ~2mins from the Core CI build time is spent with installing swift lint and format, while Edge uses ~8seconds for that. Feel free to check when you get a chance https://github.com/adobe/aepsdk-edge-ios/blob/main/.circleci/config.yml and @kevinlind can help with guidance for the setup if needed.

**Comment by emdobrin** [comment]
cc @yangyansong-adbe @shalehaha

**Comment by kevinlind** [comment]
This is how I'm installing SwiftLint, `HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint && brew cleanup swiftlint`.  Updating Homebrew can take some time so it's best to disable auto-updates for the CI nodes.

**Comment by yangyansong-adbe** [comment]
@shalehaha @emdobrin @kevinlind 
I don't think `swiftlint` can be used to check code format in CI. I have tried locally by using `swiftlint lint` command and also tried by creating a PR(https://github.com/adobe/aepsdk-edge-ios/pull/172) in Edge repo. But the following unformatted code can still pass CI.

https://github.com/adobe/aepsdk-edge-ios/pull/172/files#diff-16bb6e4ef18e2e302606606882caa26439091a2ec8fed5709310c8b89357cdd9R19
```swift
   public class Edge: NSObject, Extension {
        private let LOG_TAG = "Edge" // Tag for logging
    private var networkService: EdgeNetworkService = EdgeNetworkService()
    private var networkResponseHandler: NetworkResponseHandler?
    private var hitQueue: HitQueuing?
    private var currentPrivacyStatus: PrivacyStatus?
```
And also `swiftlint` and `swiftformat` support ignoring rules in config files, we can ignore any rules if there is a conflict.
