### ISSUE TITLE
Configuration should dispatch regular events for all update APIs and response events for getters

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#557]
### Expected Behaviour
Configuration should dispatch regular events for all update APIs and paired response events for getters.

### Actual Behaviour
Configuration returns only paired response events. The result of this is that the regular listeners don't receive config updates, as they are all paired.
Note: This does not impact the extensions using wildcard listeners, as the paired response events will be visible to them.

### Reproduce Scenario (including but not limited to)
Found while fixing https://github.com/adobe/aepsdk-core-ios/issues/551
See conversation https://github.com/adobe/aepsdk-core-ios/pull/552#issuecomment-786973893

#### Platform and Version
3.0.0

**Comment by emdobrin** [comment]
@nporter-adbe  I fixed this in my PR because the integration tests were failing for Signal and Lifecycle

**Comment by nporter-adbe** [comment]
@emdobrin Ok, you can either close my PR or merge it and bring those changes into your branch. I was under the impression that as it was a separate issue it would come in a separate PR.

In this case, I'll unassign myself from the issue and assign you.
