### ISSUE TITLE
getSharedState() will not return the latest if the given event is nil

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-ios#563]
### Expected Behaviour

```swift
    /// Retrieves the `SharedState` for a specific extension
    /// - Parameters:
    ///   - extensionName: An extension name whose `SharedState` will be returned
    ///   - event: If not nil, will retrieve the `SharedState` that corresponds with this event's version. If nil will return the latest `SharedState`
    ///   - barrier: If true, the `EventHub` will only return `.set` if `extensionName` has moved past `event`
    ///   - sharedStateType: The type of shared state to be read from, if not provided defaults to `.standard`
    /// - Returns: The `SharedState` data and status for the extension with `extensionName`
```
From the above public API doc, getSharedState() should return the latest `SharedState` if the given even is nil.

### Actual Behaviour

https://github.com/adobe/aepsdk-core-ios/blob/9fe655414c1e88d4252e9be25cf4f8d1dc539bee/AEPCore/Sources/eventhub/EventHub.swift#L233

SharedState.resolve() will return the oldest one if the event version is 0.

**Comment by nporter-adbe** [comment]
Are we sure we want to make this change and not update the doc comment?
https://github.com/adobe/aepsdk-core-ios/pull/299

**Comment by nporter-adbe** [comment]
Talked with @shalehaha the current implementation is desired, however, somehow the doc comment got out of sync. To resolve this issue I think we just need to update the doc comment.

https://github.com/adobe/aepsdk-core-ios/pull/299/files#diff-02bd1581c751b39213c003d305212478496f8a5290a1a877cef358a338c892f4R187
