### ISSUE TITLE
resetIdentities API

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#569]
The Identity Edge extension (currently alpha) has a resetIdentities API which is used to clear all the identities held by this extension as well as generating a new ECID. After a few discussions we realized that other extensions may need to reset their identities, session ids, cached content, so we are exploring to see if MobileCore can be the parent for this API that resets all the data cached locally for all the extensions, e.g. `MobileCore.resetIdentities()`.
A few examples where this can be used: 
- Identity Edge clears the IdentityMap and resets ECID
- Target extension clears session id and prefetched content
- Analytics clears AID, VID

Advantages: 
- the app developer calls one API to reset all identities in the SDK
- this API could potentially go beyond the Adobe extensions, and partners can use similar logic
- this API can be used independently from the existing privacy status settings, and allows for the possibility to sync the ECID between Identity and identity Edge
- can be used alongside the MobileCore.getSdkIdentities API

Disadvantages:
- in the future all existing extensions will need to eventually handle this reset event and clear their identities
- might be confusing to use both privacy status opted out and resetIdentities, but this can be covered in documentation and sample codes

cc @shalehaha @pfransenadb

**Comment by emdobrin** [comment]
This topic seems related to [Retrieve extension identities in a generic way](https://github.com/adobe/aepsdk-core-ios/issues/538).

**Comment by shalehaha** [comment]
We can add a new API to Core, but need to be cautious about the name. So the effect of this API can include and not limited to:
1. reset id (mcid)
2. clear id (aid, vid, identity map)
3. clear memory cache (target/offer)
4. clear data queue (identity/analytics/edge...)

**Comment by emdobrin** [comment]
I agree, if this API is not limited to resetting the identities we can have something more generic, like `MobileCore.resetSDK()` or `MobileCore.resetAll()`.

Another option we discussed is maybe allow a list of extensions that need to be reset e.g. `MobileCore.resetExtensions([Extension.Type])` but this may cause issues if there are inter-dependencies between extensions and not all the extensions are listed at once when calling this API.

**Comment by shalehaha** [comment]
The current decision is adding `MobileCore.resetIdentities()` to Core, for the purpose of clearing ids, and each extension can decide if there is anything else associated with the ids should be cleared as well. 
We can add another `reset()` method if needed in the future.
