### ISSUE TITLE
Use extension names as keys in Event Hub Shared State

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#570]
The extension name is the only unique name the SDK knows about an extension and it is recommended to be prefixed with `com.adobe.*` or for partners with the corresponding company namespace. The friendly name is something that can be used for logging or displays in the UI, but it does not guarantee it is unique.
Current docs about namespace conventions: https://aep-sdks.gitbook.io/docs/resources/building-mobile-extensions#namespace-conventions
 
Considering the above and in order to avoid possible name conflicts when registering extensions with the same friendly names, I am proposing that the Event Hub Shared State contains a map where the keys are the unique extension name, and the value is an object containing relevant information about that extension (e.g. version, friendlyName and others in the future).

Sample:
```
extensions =     {
        com.adobe.edge =         {
            version = "1.0.0";
            friendlyName = "Edge";
        };
        com.adobe.module.configuration =         {
            version = "3.0.0";
            friendlyName = "Configuration"
        };
        com.adobe.module.identity =         {
            version = "3.0.0";
            friendlyName = "Identity"
        };
        com.adobe.edge.identity =         {
            version = "1.0.0";
            friendlyName = "Identity"
        };

    } ;
```

This proposal also enables extensions to interrogate the MobileCore about the currently registered extensions, for example on bootup.
The result of MobileCore.getRegisteredExtensions() can be converted to dictionary and a quick check by extension name (e.g. com.adobe.module.identity) can be performed to validate an extension is registered. Alternatively, getSharedState("com.adobe.module.eventhub", event) can be used for the same check.

**Notes:**
- this change requires updates in Griffon UI.
- this change should be reflected in both iOS & Android MobileCore.

cc @shalehaha @pfransenadb

**Comment by emdobrin** [comment]
This item is related to [Revisit check for duplicated extensions](https://github.com/adobe/aepsdk-core-ios/issues/565).

**Comment by swarna04** [comment]
@emdobrin Based on what you are proposing if griffon were to pick up only friendly names for shared states, when both Identity and Edge Identity are present and have the same friendly name (Identity), it would be rather confusing! I'd rather we don't use friendly names at all here or use them in tandem with extension names (e.g. com.adobe.module.identity). 

<img width="662" alt="Screen Shot 2021-03-12 at 5 43 03 PM" src="https://user-images.githubusercontent.com/13000319/111014851-9a108000-835a-11eb-9fcc-994377f5860f.png">
