### ISSUE TITLE
Distribute xcframework with release assets

### ISSUE THREAD

**Issue by reline** [adobe/aepsdk-core-ios#589]
I'd like to propose having the `.xcframework` binary be precompiled and added to the Github assets for each release rather than offloading it to the client.

This would provide the option to use a direct link to pull in the `.xcframework` in as a binary target with Swift Package Manager.
e.g.
```
.binaryTarget(
   name: "AEPCore",
   url: "https://github.com/adobe/aepsdk-core-ios/releases/download/3.x.x/AEPCore.xcframework.zip",
   checksum: "xxxxx"
)
```

Thoughts?

**Comment by shalehaha** [comment]
@reline Is this mainly to save time from compiling the code?

SPM only allows you to configure either a source target or a binary target, so we have to choose only one from them. With the source target, not only it gives app developers the ability to view and debug on sdk code, it also helps extension developers with their development experience. Also, our experience of dealing with binary frameworks was not always pleasant. 
Another thing is that we will be supporting TVOS, WatchOS in the future, it will also become a blocking problem for using binaries.
So at least for now, I don't think we'd ever switch to binary target.

**Comment by reline** [comment]
Basically my team can't use the direct Github link due to red tape and as far as I am aware a git repository can't be added to our internal Artifactory either, so the remaining options with SPM is to use an `xcframework` or ditch versioning entirely (highly undesirable), download the entire source from Artifactory, drop the framework into our project, and commit it to source control.

I wasn't aware of the limitations of SPM in regards to choosing either a source or binary target.

As for TVOS and WatchOS, wouldn't just two additional targets need to be built with their own `xcframework`s? Or is that also blocked by the "single target" limitation?

Sounds like I'll have to give up on this for now if it means choosing a source target versus a binary target :(

Thanks for the timely response!

**Comment by shalehaha** [comment]
I believe SPM won't allow you to define two `AEPCore` targets with the same name, but one with source and the other with binary. So for each target, it has to be one of them.
Also, it won't work for us if we define `AEPCore` for source code and something like `AEPCoreFramework` for binary. Because all the other Adobe extensions and partner extensions depend on `AEPCore` module,  so even if you can use `AEPCoreFramework` in the app, none of the extensions will compile. 

We provide a makefile to generate xcframeworks, https://github.com/adobe/aepsdk-core-ios/blob/main/Makefile#L56, does it help? Or if for every release, if we attach the binaries to each github release, would that be helpful?

**Comment by reline** [comment]
Yeah, the binary target doesn't have to be defined in this project's `Package.swift` file, we just need to point to a hosted `xcframework` or `xcframework.zip` file. Once support is added for a new target (e.g. TVOS, WatchOS), then I believe an additional `xcframework` would be added to the release assets.

It would also be great to have the checksum for each framework added to the release notes, for convenience.
```sh
swift package compute-checksum <path-to-zip>
```

**Comment by shalehaha** [comment]
@reline 

https://github.com/adobe/aepsdk-core-ios/releases/tag/3.1.0, I did it for the new 3.1.0 release, please let me know whether this works for you.

**Comment by reline** [comment]
Hey sorry for the late response, I did attempt to pull down the `xcframework` as a binary target using XCode 12.4 and Swift 5.3, but received a vague error when attempting to build, was maybe hoping for some insight:

> There is no XCFramework found at '~/Library/Developer/Xcode/DerivedData/MyProject-barneedfeittgfgipnalqmxlilke/SourcePackages/artifacts/Adobe/AEPCore.xcframework'.

Here's my current `Package.swift`.
I managed to pull the binary down, but adding it as a dependency (`dependencies: ["AEPCore"]),`) breaks the build.
```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let version = "3.1.0"

let package = Package(
    name: "Adobe",
    platforms: [.iOS(.v10)],
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "Adobe",
            targets: ["Adobe"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "Adobe",
            dependencies: ["AEPCore"]),
        .binaryTarget(
            name: "AEPCore",
            url: "https://github.com/adobe/aepsdk-core-ios/releases/download/\(version)/AEPCore.xcframework.zip",
            checksum: "236b38241df81c49f4087a643944eef89b061bc6ed4003f1c58d5fb2a8a8809a"
        ),
        .testTarget(
            name: "AdobeTests",
            dependencies: ["Adobe"]),
    ]
)
```

**Comment by shalehaha** [comment]
@reline 
I made a mistake when packaging the zip files. Can you try again with the builds in 3.1.1 release, https://github.com/adobe/aepsdk-core-ios/releases/tag/3.1.1 ?

**Comment by reline** [comment]
I still see the same error
> There is no XCFramework found at '/Users/czym1t/Library/Developer/Xcode/DerivedData/OVITestDrive-barneedfeittgfgipnalqmxlilke/SourcePackages/artifacts/Adobe/AEPCore.xcframework'.

but now I do see the framework in the DerivedData
`~/Library/Developer/Xcode/DerivedData/MyProject-barneedfeittgfgipnalqmxlilke/SourcePackages/artifacts/Adobe/build/AEPCore.xcframework`

Looks like it's off by one directory. Manually moving it up one directory successfully builds.

**Comment by shalehaha** [comment]
@reline 
That was what I have fixed in 3.1.1 builds.  Looks like xcode didn't download the binaries from 3.1.1 release, can you trying cleaning the project?

**Comment by reline** [comment]
Yup! I just deleted the DerivedData for that folder and it worked like a charm, thanks!

**Comment by reline** [comment]
I did get a build issue when importing into my Swift package, but I think it's just an incompat issue on my side.
> Failed to build module 'AEPCore' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

**Comment by shalehaha** [comment]
@reline 
We've just fixed an issue that might cause this compile error, would you mind trying out the new 3.1.2 version?

**Comment by reline** [comment]
I tried the latest release but I'm seeing the same issue and it looks like the version in the plist is still 3.1.1
https://github.com/adobe/aepsdk-core-ios/releases/download/3.1.2/AEPCore.xcframework.zip

**Comment by shalehaha** [comment]
@reline 
oops, my bad, attached the wrong version. Can you try again? 
If you are still seeing errors, can you attach the screenshot of all the errors from Xcode?

**Comment by reline** [comment]
Thanks, the version looks right now. Here's the errors I'm seeing with 3.1.2.
Importing `AEPServices` by itself seems to build fine, I see identical errors with every other combination of imports.

<img width="925" alt="Screen Shot 2021-05-03 at 2 55 25 PM" src="https://user-images.githubusercontent.com/9147055/116938425-9b09b380-ac1f-11eb-9850-135a86121351.png">

<img width="923" alt="Screen Shot 2021-05-03 at 2 56 03 PM" src="https://user-images.githubusercontent.com/9147055/116938470-afe64700-ac1f-11eb-8aca-1a9a45d77a92.png">

<img width="931" alt="Screen Shot 2021-05-03 at 2 55 46 PM" src="https://user-images.githubusercontent.com/9147055/116938445-a5c44880-ac1f-11eb-957a-94fc0ff07af6.png">

**Comment by shalehaha** [comment]
@reline 
Do you mind to try again with the https://github.com/adobe/aepsdk-core-ios/releases/tag/3.1.3 builds?

**Comment by reline** [comment]
Thanks a ton, that worked! I'll let you know if I have any other issues down the road.
This will help us move away from CocoaPods and avoid workspaces.
