### ISSUE TITLE
Multiple EventHub shared states posted on registerExtensions(..)

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#596]
### Expected Behaviour
When calling MobileCore.registerExtension(extensions, completion) the MobileCore registers all the provided extensions, creates the Event Hub Shared state with version 0 with the registered extensions and starts the Event Hub for processing.

### Actual Behaviour
When calling MobileCore.registerExtension(extensions, completion) and using the compat layer the MobileCore posts multiple Event Hub shared states (see version 0 and 9 in the logs below).

This issue has the side effect of breaking the check for registered extensions from other extensions, such as Edge checking for the presence of Consent on boot. 

#### Steps to Reproduce
Run the Swift sample app and inspect the logs https://github.com/adobe/aepsdk-sample-app-ios/tree/main/Swift/AEPSampleApp

#### Platform and Version
See app's podfile 

#### Sample Code that illustrates the problem
See AppDelegate

#### Logs taken while reproducing problem

<details>
  <summary>Logs, click to expand</summary>

 2021-04-05 12:21:40.719347-0700 AEPSampleApp[71083:1263855] [AEP SDK DEBUG - <EventHub>] Shared state created for com.adobe.module.eventhub with version 0 and data: 
{
  "version" : "3.1.0",
  "extensions" : {
    "com.adobe.assurance" : {
      "version" : "1.1.0",
      "friendlyName" : "com.adobe.assurance"
    },
    "com.adobe.module.lifecycle" : {
      "friendlyName" : "Lifecycle",
      "version" : "3.1.0"
    }
  }
}
2021-04-05 12:21:40.733977-0700 AEPSampleApp[71083:1263870] [AEP SDK DEBUG - <EventHub>] Shared state created for com.adobe.module.eventhub with version 9 and data: 
{
  "version" : "3.1.0",
  "extensions" : {
    "com.adobe.edge.identity" : {
      "version" : "1.0.0",
      "friendlyName" : "Edge Identity"
    },
    "com.sampleCompany.module.sample" : {
      "version" : "1.0.0",
      "friendlyName" : "Sample"
    },
    "com.adobe.module.configuration" : {
      "version" : "3.1.0",
      "friendlyName" : "Configuration"
    },
    "com.adobe.module.signal" : {
      "friendlyName" : "Signal",
      "version" : "3.1.0"
    },
    "com.adobe.assurance" : {
      "friendlyName" : "com.adobe.assurance",
      "version" : "1.1.0"
    },
    "com.adobe.edge" : {
      "version" : "1.1.0",
      "friendlyName" : "AEPEdge"
    },
    "com.adobe.edge.consent" : {
      "friendlyName" : "Consent",
      "version" : "1.0.0"
    },
    "com.adobe.module.userProfile" : {
      "friendlyName" : "UserProfile",
      "version" : "3.0.0"
    },
    "com.adobe.module.identity" : {
      "version" : "3.1.0",
      "friendlyName" : "Identity"
    },
    "com.adobe.module.lifecycle" : {
      "friendlyName" : "Lifecycle",
      "version" : "3.1.0"
    }
  }
}
</details>

**Comment by nporter-adbe** [comment]
@shalehaha What is happening here is that the compat layer calls `MobileCore.registerExtension(...)` this, in turn, tells the event hub to share state. So when you register a legacy 3rd party extension with native swift extensions you end up with an extra shared state shared by the event hub. https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/core/MobileCore.swift#L82

We could easily fix this by adding a check in EventHub.shareEventHubSharedState to only share event hub state if the event hub is started.
https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/eventhub/EventHub.swift#L261

Another option is to provide an API `isExtensionRegistered(...)` which doesn't depend on the EventHub shared state.

I feel that the current behavior isn't exactly expected but it seems to me that the Edge extension depends too much on assumptions about the EventHub in this situation. Publishing an additional shared state from the event hub should not cause issues for extensions unless the extension is making an assumption about something that isn't in the event hub contract. 

thoughts?

**Comment by shalehaha** [comment]
`adding a check in EventHub.shareEventHubSharedState to only share event hub state if the event hub is started.`, I like this option.
