### ISSUE TITLE
Identity blocked on first launch when config invalid

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#608]
### Expected Behaviour
Identity should wait until the first valid config is available (with orgid and privacy status) to process the force sync event.

### Actual Behaviour
Currently the force sync event is blocked by the first invalid config, no other events are processed after that.

#### Steps to Reproduce

- fresh app install 
- I set first config with missing orgid MobileCore.updateConfigurationWith(configDict: [“dummy”: “config”])
- I set second config with valid orgid MobileCore.configureWith(appId: self.LAUNCH_ENVIRONMENT_FILE_ID) - which provides valid orgid
- Identity extension does not generate ECID, all the processing that requires identity is blocked

#### Platform and Version
Identity 3x extension

#### Sample Code that illustrates the problem

```
let extensions = [AEPIdentity.Identity.self,
                  Lifecycle.self,
                  Signal.self,
                  Edge.self,
                  Consent.self,
                  AEPEdgeIdentity.Identity.self
                  //step-extension-start
                  , SampleExtension.self
                  //step-extension-end
                  , UserProfile.self
                  // step-assurance-start
                  , AEPAssurance.self
                  // step-assurance-end
                ]

MobileCore.registerExtensions(extensions, {
    // Use the App id assigned to this application via Adobe Launch
    MobileCore.configureWith(appId: self.LAUNCH_ENVIRONMENT_FILE_ID)
    
    if appState != .background {
        // only start lifecycle if the application is not in the background
        MobileCore.lifecycleStart(additionalContextData: ["contextDataKey": "contextDataVal"])
    }
})

MobileCore.updateConfigurationWith(configDict: ["dummy": "config"]) // this gets executed before the registerExtensions callback and blocks processing
```

**Comment by nporter-adbe** [comment]
Likely solution: Fetch latest configuration shared state during bootup process of Identity rather than the config versioned at the first event.
