### ISSUE TITLE
No ECID when opt-in after opt-out in Identity shared state

### ISSUE THREAD

**Issue by shtomar-adb** [adobe/aepsdk-core-ios#639]
### Expected Behaviour
If app opt-in after opt-out, app should receive ECID in identity shared state

### Actual Behaviour
If app opt-in after opt-out, Identity shared state doesn't contains the ECID. When opt-in is done second time then Identity shared state contains ECID.

**Comment by nporter-adbe** [comment]
@shtomar-adb I ran our sample app and when I opt-in after being opt-out I see a new ECID included in the Identity shared state.

Here is the shared state after changing privacy to opt-out, which does not contain an ECID as expected.
```json
2021-05-28 10:55:45.724025-0600 AEPSampleApp[21587:11571142] [AEP SDK DEBUG - <EventHub>] Standard shared state created for com.adobe.module.identity with version 91 and data: 
{
  "lastsync" : 1622220813.3747649
}
```

Here is the log from Identity after changing to opt-in, which contains the ECID:
```json
2021-05-28 10:56:49.766038-0600 AEPSampleApp[21587:11571227] [AEP SDK DEBUG - <EventHub>] Standard shared state created for com.adobe.module.identity with version 96 and data: 
{
  "blob" : "j8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI",
  "lastsync" : 1622221009.7656798,
  "mid" : "03236312170745520675786750585880425528",
  "locationhint" : "9"
}
```

I'm not able to reproduce this issue. Please provide some steps to reproduce this issue or create a sample app that demonstrates it. Logs for this issue would also be helpful.
