### ISSUE TITLE
Update release process to capture version updates per extension

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#650]
Current release process requires all the extension versions to be updated at the same time. To better reflect the changes made in each extension for an app developer, we need to provide the flexibility of updating only one extension at a time.

For example when a bug fix or a new API is added for a certain extension, the other extensions don't need to be updated and their version will remain unchanged.

**Comment by praveek** [comment]
We currently update the versions together, primarily for SPM. We should look into separating each extension into its own repository instead of managing separate extension versions.
