### ISSUE TITLE
Unimplemented code in AEPCore - Critical for migration V4 -> V5

### ISSUE THREAD

**Issue by neyroja** [adobe/aepsdk-core-ios#654]
### Expected Behaviour

After migrating from previous V4 (AdobeMobileLibrary 4.19.2) to V5 (AEP main) all ID are migrated and sync.

### Actual Behaviour

VisitorID no migrated

#### Platform and Version

Migration 
from: AdobeMobileLibrary 4.19.2 
to : AEP main

#### Suspicious Code that illustrates the problem

MigratorV4.migrateVisitorIdLocalStorage
https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/migration/V4Migrator.swift

MigratorV5. migrateVisitorIdLocalStorage
https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/migration/V5Migrator.swift
![AEP_MigrationV4_1](https://user-images.githubusercontent.com/86352553/123083297-377e5400-d420-11eb-9dae-5fe5de077f7a.png)
![AEP_MigrationV4](https://user-images.githubusercontent.com/86352553/123083303-38af8100-d420-11eb-96f7-13127497ff58.png)
![AEP_MigrationV5](https://user-images.githubusercontent.com/86352553/123083305-39481780-d420-11eb-8671-e585b783d975.png)

**Comment by nporter-adbe** [comment]
@neyroja This functionality is implemented within each of the own extensions now. We should go through and clean up the TODOs as they are no longer needed. 

Analytics: https://github.com/adobe/aepsdk-analytics-ios/blob/b9121586e787a3700fbaba319304b34df2e7aab9/AEPAnalytics/Sources/AnalyticsMigrator.swift
Audience: https://github.com/adobe/aepsdk-audience-ios/blob/main/AEPAudience/Sources/AudienceMigrator.swift
Target: https://github.com/adobe/aepsdk-target-ios/blob/dev/AEPTarget/Sources/TargetV4Migrator.swift
https://github.com/adobe/aepsdk-target-ios/blob/dev/AEPTarget/Sources/TargetV5Migrator.swift

Are you experiencing issues regarding migration from v4?
