### ISSUE TITLE
Remove dependencies preventing tvOS build

### ISSUE THREAD

**Issue by mmcnabb2187** [adobe/aepsdk-core-ios#663]
### Expected Behaviour
AEPServices builds tvOS target
### Actual Behaviour
AEPServices build on tvOS fails
#### Steps to Reproduce
Build AEPCore schemes for tvOS device or simulator
#### Platform and Version
macOS 11.4, Xcode 12
#### Logs taken while reproducing problem
WebKit is not available when building for tvOS. Consider using `#if !os(tvOS)` to conditionally import this framework.
CoreTelephony is not available when building for tvOS. Consider using `#if !os(tvOS)` to conditionally import this framework.

**Comment by nporter-adbe** [comment]
@mmcnabb2187 Currently tvOS is not supported by this SDK yet. 

@praschetan care to provide roadmap insight on tvOS?

**Comment by mmcnabb2187** [comment]
Hi again,
This is becoming an issue for us.  Using the Obj-c SDKs is a problem due to the use of static libraries.  Linking them to both the app and a dynamic framework it includes results in tracking calls not being sent.

**Comment by praveek** [comment]
I have added #707 to our backlog for supporting tvOS. We have not yet prioritized it and will update this issue once we do.

**Comment by praveek** [comment]
The latest release [v3.7.0](https://github.com/adobe/aepsdk-core-ios/releases/tag/3.7.0) adds support for tvOS.
