### ISSUE TITLE
Clean-up random test failures

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-ios#678]
### Actual Behaviour

Test failed at this line of code -> 
https://github.com/adobe/aepsdk-core-ios/blob/69b84a324117d4547fb19fd0033aa033b8571466/AEPIntegrationTests/IdentityIntegrationTests.swift#L254

[log.txt](https://github.com/adobe/aepsdk-core-ios/files/6902704/log.txt)

**Comment by cdhoffmann** [comment]
Another one: `RulesEngineFunctionalTests.testLoadRulesFromLocalCacheFile()`

**Comment by cdhoffmann** [comment]
`testSetAdvertisingIdentifiers` is failing intermittently in the CI as well.

**Comment by sbenedicadb** [comment]
`ConfigurationIntegrationTests.testClearUpdatedConfigFromSetPrivacyStatus()`

https://app.circleci.com/pipelines/github/adobe/aepsdk-core-ios/1797/workflows/0cac3495-8619-4383-8712-f3d86c1959c8/jobs/2222
