### ISSUE TITLE
Fix Logging around Downloading Rules

### ISSUE THREAD

**Issue by cdhoffmann** [adobe/aepsdk-core-ios#698]
When downloading rules, if we hit a 304 not modified response in the `RulesDownloader`'s `loadRulesFromUrl`, we call the completion block with nil passed in. This leads to the `LaunchRulesEngine`'s `replaceRules` function to log: "Failed to load rules from url" which is confusing to customers as they think something has gone wrong, when the cached rules have already been loaded in this scenario. We should make sure that this is not logged when a 304 occurs. Another scenario is that we log "Loading App id From Manifest failed" as an error when we try to initially load the appid from cache / manifest before we have downloaded the config. This log is misleading and needs to be fixed as well.

**Comment by emdobrin** [comment]
We should revisit these log messages and evaluate if debug/warning level can be used instead of error since the consequence is handled gracefully here.
Applies for : processAttachDataConsequence, processModifyDataConsequence, processDispatchConsequence
