### ISSUE TITLE
Add tvOS Support 

### ISSUE THREAD

**Issue by praveek** [adobe/aepsdk-core-ios#707]
- Add tvOS support to AEPServices
- Add tvOS support for Core extensions
- Add tvOS target to sample apps

**Comment by mmcnabb2187** [comment]
We would like to see this prioritized.  We have a number of projects that need to update and are finding it problematic to use the static ACP* libraries.  Thank you.

**Comment by objectiveCarlo** [comment]
Hello are there any updates on this issue? Thank you.

**Comment by praveek** [comment]
@objectiveCarlo We are planning to add tvOS support by end of July.

**Comment by alexzchut** [comment]
@praveek I am using AEP with iOS and need this also for tvOS to be used with several client's apps so I prepared PRs with changes needed to allow tvOS support, 
in core one - preventing access to iOS only related stuff, on others just adding tvOS in podspec. 
I see that events are being sent correctly so please take a look if this can help to release tvOS version sooner.

Thanks!
 
https://github.com/adobe/aepsdk-core-ios/pull/798
https://github.com/adobe/aepsdk-rulesengine-ios/pull/52
https://github.com/adobe/aepsdk-analytics-ios/pull/69
https://github.com/adobe/aepsdk-media-ios/pull/53

**Comment by praveek** [comment]
Thanks for the contribution @alexzchut. We have planned to release tvOS support for Core, Analytics and Media around July. As part of the official release, we are also working on updating few services, sample apps, allow using it from cocoapods, spm and also certifying the builds on device. 

cc @praschetan

**Comment by wryphonedev** [comment]
@praveek Any chance we'll see this merged and released soon? As we try to adopt Analytics on iOS and tvOS, we either need this published solution or we have to diverge our project and have tv integrate a much older sdk.
