### ISSUE TITLE
Latest 3.4.0 release fails to build

### ISSUE THREAD

**Issue by tadija** [adobe/aepsdk-core-ios#769]
### Expected Behaviour
no build errors

### Actual Behaviour
has build errors

#### Steps to Reproduce
try to build

#### Platform and Version
Xcode 13.2.1

#### Logs taken while reproducing problem

Hi, in case you didn't notice, there is a build error in the latest 3.4.0 release.

**Comment by praveek** [comment]
@tadija I am able to build the project in Xcode 13.2.1. Can you provide more details on the build error you are seeing?

**Comment by tadija** [comment]
Have you tried adding AEPCore as a dependency via SPM? This is what happens and it pretty much seems that there is a build error in your code:

<img width="1473" alt="Screenshot 2022-01-26 at 15 30 05" src="https://user-images.githubusercontent.com/2762374/151181765-ab3ecf77-a788-49fb-8875-fd2949dbd9c1.png">

**Comment by praveek** [comment]
@tadija Can you update your AEPRuleEngine dependency to 1.1.0? If it is already in latest version, try building once after cleaning build folder. Let me know if this works.

**Comment by tadija** [comment]
I don't define that dependency, it must be that one of these (from my Package.swift) is using the outdated version of it:

```
.package(
    name: "AEPCore",
    url: "https://github.com/adobe/aepsdk-core-ios.git",
    from: "3.4.0"
),
.package(
    name: "AEPUserProfile",
    url: "https://github.com/adobe/aepsdk-userprofile-ios.git",
    from: "3.0.1"
),
.package(
    name: "AEPAnalytics",
    url: "https://github.com/adobe/aepsdk-analytics-ios.git",
    from: "3.0.3"
),
```

**Comment by praveek** [comment]
@tadija It happens because we missed updating [this dependency](https://github.com/adobe/aepsdk-core-ios/blob/main/Package.swift#L29) correctly for v3.4.0. I will update it and release a patch. 
As a workaround run `swift package update` and it should update to the latest version of `AEPRulesEngine`

**Comment by tadija** [comment]
thank you, I'll just wait for that update

**Comment by praveek** [comment]
@tadija AEPCore v3.4.1 fixes this issue.

**Comment by tadija** [comment]
I can confirm that this is fixed.
