### ISSUE TITLE
Inconsistent case of push identifier is submitted to ACS from ACP

### ISSUE THREAD

**Issue by chankiyu22** [adobe/aepsdk-core-ios#786]
### Expected Behaviour

The push identifier submitted from ACP and AEP should be in the same case (either uppercased or lowercased).

### Actual Behaviour

The push identifier submitted from AEP is in lowercase, while that from ACP is in uppercase.

|![](https://user-images.githubusercontent.com/3663179/160050083-b849095e-3c4f-4aae-80e6-605bc0c759be.png)|
|---|

#### In AEP

> setPushIdentifier
>
> https://github.com/adobe/aepsdk-core-ios/blob/3.3.1/AEPCore/Sources/core/MobileCore.swift#L154-L155
>
> hexDescription
>
> https://github.com/adobe/aepsdk-core-ios/blob/3.3.1/AEPCore/Sources/core/Data+HexString.swift#L18-L20

We can see the the device token data is formatted to lowercased hex string using format `%02x` (lowercase "x").

#### In ACP

> setPushIdentifier
>
> https://github.com/adobe/react-native-acpcore/blob/v2.0.0/ios/src/Core/RCTACPCore.m#L108-L110
>
> https://github.com/Adobe-Marketing-Cloud/acp-sdks/search?q=setpushidentifier

The files are built to binary file so no further tracking down. But lowercasing the token seems will still submit an uppercased token to ACS. We believe ACP use the same method with format `%02X` (uppercase "X").

#### Platform and Version

Platform: iOS

- @adobe/react-native-acpcore: 2.0.0

- AEP MobileCore: 3.3.1

#### Sample Code that illustrates the problem

In ACP,

```objc
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [ACPCore setPushIdentifier:deviceToken];
}
```

In AEP,

```swift
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
  MobileCore.setPushIdentifier(deviceToken)
}
```

**Comment by cdhoffmann** [comment]
@chankiyu22 Thank you for reporting this issue. It has been fixed and will be included in our next release.
