### ISSUE TITLE
Fix intermittent failures in Configuration integration tests

### ISSUE THREAD

**Issue by cdhoffmann** [adobe/aepsdk-core-ios#822]
Configuration integration tests have been failing intermittently. Look into why, and fix them.

**Comment by cdhoffmann** [comment]
After investigating, it looks like all the failures originate from our [initExtensionsAndWait()](https://github.com/adobe/aepsdk-core-ios/blob/main/AEPIntegrationTests/ConfigurationIntegrationTests.swift#L50) timing out. I have not been able to reproduce this locally and so it is very difficult to know why it is taking so long to register the extensions. Leaving open for now until we can reproduce locally.

**Comment by praveek** [comment]
Reopen with a link to Circle CI failure, if the issue still happens.
