### ISSUE TITLE
Identity behavior change request: Identity extension should not have a hard dependency on Analytics

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-ios#845]
https://github.com/adobe/aepsdk-core-ios/blob/55d208283eed4f99b5fe8ed75940fcc03b0511a1/AEPIdentity/Sources/Identity.swift#L83-L88
Currently, `getUrlVariables` and `appendToUrl` events can block the Identity events processing if the Analytics extension is not registered. We can consider dropping those events if the customer's app doesn't have Analytics installed/registered.

cc @praveek @emdobrin @kevinlind

**Comment by praveek** [comment]
Identity waits for shared state when analytics extension is registered. `getSharedState` returns nil when analytics extension is not registered.
