### ISSUE TITLE
AEPLifecycle-Swift.h Error Mac M1

### ISSUE THREAD

**Issue by salvatoreboemia** [adobe/aepsdk-core-ios#883]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Hi,

when I tried to build my project on M1 Mac I got this error

<img width="259" alt="Screenshot 2023-02-28 at 09 52 10" src="https://user-images.githubusercontent.com/20614870/221803826-77626948-e5d7-4139-b003-dc38bcf886b5.png">

AEP is installed by SPM of course

Some hint in order to fix this issue? 

Thanks

### Environment

AEP Core 3.7.0
XCode 14.2

**Comment by salvatoreboemia** [comment]
> Hi @salvatoreboemia, I was not able to reproduce this issue on my side using the M1 Mac. Can you provide steps to reproduce? Also verify that app is built for iOS/tvOS device. If you see this error on iOS/tvOS then please post the device name and OS version as well.
> 
> Thanks, Arjun

Hi

I just tried to build the project (only for iOS) on the simulator, and, **without** rosetta, I got the error in the screenshot.

It's only a settings issue on my project?

thanks for you help

**Comment by cdhoffmann** [comment]
@salvatoreboemia Could you share the following build settings **Build Settings -> Architectures**
![Screenshot 2023-03-09 at 11 04 45 AM](https://user-images.githubusercontent.com/10753118/224116378-c8cdb976-18df-44d2-8c43-2d25343db35a.png)

**Comment by salvatoreboemia** [comment]
> @salvatoreboemia Could you share the following build settings **Build Settings -> Architectures** ![Screenshot 2023-03-09 at 11 04 45 AM](https://user-images.githubusercontent.com/10753118/224116378-c8cdb976-18df-44d2-8c43-2d25343db35a.png)

Sure

<img width="734" alt="Screenshot 2023-03-10 at 10 38 15" src="https://user-images.githubusercontent.com/20614870/224281116-8af79cca-8296-491e-a067-082c0480367c.png">

<img width="736" alt="Screenshot 2023-03-10 at 10 38 23" src="https://user-images.githubusercontent.com/20614870/224281153-0fde1719-1f12-4c19-95a4-c890b05eda1a.png">

<img width="720" alt="Screenshot 2023-03-10 at 10 38 28" src="https://user-images.githubusercontent.com/20614870/224281186-d931c22d-f503-4da6-9695-c3ca36e1f1ae.png">

**Comment by cdhoffmann** [comment]
@salvatoreboemia Why are you excluding the arm64 architecture? Could you try removing that from the excluded architectures and seeing if that fixes the issue?

**Comment by cdhoffmann** [comment]
@salvatoreboemia Were you able to try my suggestion?

**Comment by salvatoreboemia** [comment]
> @salvatoreboemia Were you able to try my suggestion?

Ops sorry for late reply

Yes I solved with your suggestion

Basically your suggestion allow me to understand the real problems

2 SDK (not adobe) 

You save my time!!! 

Thanks

**Comment by cdhoffmann** [comment]
@salvatoreboemia Great to hear.
