### ISSUE TITLE
How i setTntId method Target user ID (also known as the tntId) Using ACP 2.X (OBJECTIVE-C). 

### ISSUE THREAD

**Issue by shravanteegala** [adobe/aepsdk-core-ios#915]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Using ACP 2.X (OBJECTIVE-C).

In ACPTarget.h file we have  below getter methods.

+ (void) getThirdPartyId: (nonnull void (^) (NSString* __nullable thirdPartyId)) callback;
+ (void) getTntId: (nonnull void (^) (NSString* __nullable tntId)) callback;

And setter method setThirdpartyID is there.
+ (void) setThirdPartyId: (nullable NSString*) thirdPartyId;

But I need to set Target user ID (also known as the tntId) tntID. 
So How I get these tntId is it coming (getting) automatically or any other option .?
Please help me.

### Environment

Xcode 13.4

**Comment by cdhoffmann** [comment]
Hey there @shravanteegala. Please don't create duplicate tickets in different repositories. It looks like your question was answered in the [correct place](https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/687).

**Comment by shravanteegala** [comment]
sorry. @cdhoffmann 
sure.
