### ISSUE TITLE
Signal fails to read HTTP_SUCCESS_CODES Range in obj-c app

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-ios#956]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

The constant uses Range definition in swift which seems to cause an issue for objc app. Check options for conversion to NSRange or contain the success code usages to the Signal extension

<img width="2272" alt="signal_error" src="https://github.com/adobe/aepsdk-core-ios/assets/33132425/57cebdeb-c82f-416f-9004-cc4b7aa4f389">

### Environment

OS: iOS 16.4
SDK(s): AEPCore 4.0.0, AEPServices 4.0.0, AEPSignal 4.0.0
IDE: Xcode 14.3.1

### Steps to reproduce

Pod install and run Objc sample app - https://github.com/adobe/aepsdk-sample-app-ios/tree/main/Obj-C
```
$ cd Obj-C/
$ pod install
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
Ignoring gherkin-2.12.2 because its extensions are not built. Try: gem pristine gherkin --version 2.12.2
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.12.0) is higher than the version of the current executable (1.11.2). Incompatibility issues may arise.
Downloading dependencies
Installing AEPAssurance 4.0.0 (was 3.0.0)
Installing AEPCore 4.0.0 (was 3.3.0)
Installing AEPIdentity 4.0.0 (was 3.3.0)
Installing AEPLifecycle 4.0.0 (was 3.3.0)
Installing AEPRulesEngine 4.0.0 (was 1.0.1)
Installing AEPServices 4.0.0 (was 3.3.0)
Installing AEPSignal 4.0.0 (was 3.3.0)
Removing AEPAudience
Generating Pods project
Integrating client project
Pod installation complete! There are 5 dependencies from the Podfile and 7 total pods installed.
```

**Comment by emdobrin** [comment]
It looks like the  error was surfaced with my setup after I updated to latest commit on main branch, and I had 3.x dependencies installed prior to that, I am not able to reproduce with a fresh app download now. Chris confirmed this constant [was added in 3.4.3](https://github.com/adobe/aepsdk-core-ios/pull/779), which leads us to believe this was rather a project cleanup issue after the pods update.

**Comment by cdhoffmann** [comment]
Closing as can't be reproduced with a clean build and pod update. Most likely a cache issue as @emdobrin mentioned.
